name: Spring Boot Gradle Test Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure docker-compose.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./docker-compose.yml
        env:
          services.mysql.environment.MYSQL_DATABASE: ${{secrets.TEST_DATABASE}}
          services.mysql.environment.MYSQL_ROOT_PASSWORD: ${{secrets.TEST_DB_PASSWORD}}
          services.minio.environment.MINIO_ROOT_USER: ${{secrets.STORAGE_USER}}
          services.minio.environment.MINIO_ROOT_PASSWORD: ${{secrets.STORAGE_PASSWORD}}

      # Build and start container
      - name: Build and Start Container
        run: docker-compose up -d

      # java ì„¤ì¹˜
      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'liberica'

      # í™˜ê²½ ë³€ìˆ˜ ì ìš©
      - name: Configure application.yaml under test directory
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yaml
        env:
          spring.datasource.url: jdbc:mysql://localhost:3308/${{secrets.TEST_DATABASE}}
          spring.datasource.username: ${{secrets.TEST_DB_USERNAME}}
          spring.datasource.password: ${{secrets.TEST_DB_PASSWORD}}
          spring.minio.bucket: ${{secrets.STORAGE_BUCKET}}
          spring.minio.access-key: ${{secrets.STORAGE_USER}}
          spring.minio.secret-key: ${{secrets.STORAGE_PASSWORD}}

      # gradle ê¶Œí•œ ì¶”ê°€
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # í”„ë¡œì íŠ¸ ë¹Œë“œ
      - name: Build with Gradle
        run: ./gradlew clean build

      # Jacoco í…ŒìŠ¤íŠ¸ ê²°ê³¼ ì¶”ê°€
      - name: ğŸ“‘ Jacoco í…ŒìŠ¤íŠ¸ ê²°ê³¼
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{github.workspace}}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
