name: Spring Boot Gradle Test Workflow
on:
  pull_request:
    branches:
      - merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure docker-compose.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yaml
        env:
          services.environment.MYSQL_DATABASE: ${{ secrets.TEST_DATABASE }}
          services.environment.MYSQL_PASSWORD: ${{ secrets.TEST_DB_USERNAME }}
          services.environment.MYSQL_ROOT_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}

      # Build and start container
      - name: Build and Start Container
        run: docker-compose up -d

      # Build and start container
      - name: Docker ps
        run: docker ps

      # java 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'liberica'

      # 환경 변수 적용
      - name: Configure application.yaml under test directory
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yaml
        env:
          spring.datasource.url: jdbc:mysql://localhost:3308/${{ secrets.TEST_DATABASE }}
          spring.datasource.username: ${{ secrets.TEST_DB_USERNAME }}
          spring.datasource.password: ${{ secrets.TEST_DB_PASSWORD }}

      # gradle 권한 추가
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 프로젝트 빌드
      - name: Build with Gradle
        run: ./gradlew clean build
