name: Spring Boot Gradle Test Workflow
on:
  pull_request:
    branches:
      - merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: checking pwd
        run: echo "pwd"

      # Build and start container
      - name: Build and Start Container
        run: docker-compose up -d

      # java 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'liberica'

      # 환경 변수 적용
      - name: Configure application.yaml under test directory
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yaml
        env:
          spring.datasource.url: jdbc:mysql://localhost:3306/${{ secrets.TEST_DATABASE }}
          spring.datasource.username: ${{ secrets.TEST_DB_USERNAME }}
          spring.datasource.password: ${{ secrets.TEST_DB_PASSWORD }}

      # gradle 권한 추가
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # run 명령어로 schema 만드는 명령어 실행
      - name: Into Schema
        run: mysql -h localhost -P 3306 -u ${{secrets.TEST_DB_USERNAME}} -p${{secrets.TEST_DB_PASSWORD}} --protocol=tcp < ./mysql/schema.sql

      # 프로젝트 빌드
      - name: Build with Gradle
        run: ./gradlew clean build
